param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C-SPY Debugger, as an aid to running the cspybat command line utility
# using the appropriate settings.
#
# Note that this file and the accompanying launch.json file are generated
# every time the workspace is opened or a setting is changed, so you
# may want to move or rename the files before making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the
# name of this batch file, optionally followed by the name of the debug
# file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C-SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "D:\Users\chen_\AppData\Local\iar\ewarm-10.10.2\common\bin\CSpyBat.exe" --launch_file "D:\Users\chen_\Documents\My_Project\FOC\STM32_FOC_Source\STFOC_Streamline\IAR\settings\launch.json" --launch_config "example - Release" 
}
else
{
& "D:\Users\chen_\AppData\Local\iar\ewarm-10.10.2\common\bin\CSpyBat.exe" --launch_file "D:\Users\chen_\Documents\My_Project\FOC\STM32_FOC_Source\STFOC_Streamline\IAR\settings\launch.json" --launch_config "example - Release" --debug_file=$debugfile 
}
